baseURL = "https://liguangchang.cn"
languageCode = "en-us"
theme = "hello-friend-ng"
paginate = 50

PygmentsCodeFences = true
PygmentsStyle = "monokai"
hasCJKLanguage = true


enableEmoji = true
disable404 = false

[blackfriday]
  hrefTargetBlank = true

[params.utterances]
    owner = "lgc523"
    repo = "hugo-comment"

[params]
	showReadingTime = true

	dateform = "01-02"
	dateformShort = "01-02"
	dateformNum = "2006-01-02"
	dateformNumTime = "2006-01-02 15:04"

	homeSubtitle = "Javaã€Goã€Server-Side"
	
	disableReadOtherPosts = false
	enableShareButtons = true	
	enableThemeToggle = true


	[[params.social]]
		name = "github"
		url  = "https://github.com/lgc523"

	[[params.social]]
		name = "email"
		url  = "mailto:lgc523@126.com"



[params.footer]
	topText = ["Powered by Hugo Â· hello-friend-ng"]
	bottomText = [' &#183; <a href="https://beian.miit.gov.cn">äº¬ICPå¤‡2020035531å·-2</a> &#183; <a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=41012202000328" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;">']
 
[author]
	name = "lgc523"

[taxonomies]
	category = "blog"
	tag = "tags"
	series = "series"
	
[languages]
	[languages.en]
		title = "ğŸ«¥ğŸŒ¦ğŸâ™¨ï¸ğŸ˜¶â€ğŸŒ«ï¸"
		readOtherPosts = "Read other posts"
		newerPosts = "Newer"
		olderPosts = "Older"
		readMore = "Read more"
		menuMore = "Show more"
		dateFormatSingle = "2006-01-02"
		dataFormatList = "2006-01-02"

		[languages.en.params.logo]
			logoText = "$ Keep simple,keep Stupid"
			logoHomeLink = "/"
			logoCursorColor = "#1b1c1d"
			logoCursorANimate = "5s"

	[[menu.main]]
		identiier = "|"
		name = "|"
		url = "/"
		weight = 10
	
	[[menu.main]]
		identifier = "posts"
		name = "post"
		url = "/posts"
		weight = 11

	[[menu.main]]
		identifier = "about"
		name = "about"
		url = "/about"
		weight = 12
		
